# Generated by Django 4.0.3 on 2022-03-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30, verbose_name='Nomi')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picture_type')),
            ],
        ),
    ]
