# Generated by Django 4.0.3 on 2022-03-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_alter_pictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(upload_to='Images/', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.picture_type'),
        ),
    ]
