# Generated by Django 4.0.3 on 2022-04-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_alter_pictures_image_alter_pictures_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Img'),
        ),
    ]
