# Generated by Django 4.0.3 on 2022-04-11 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_alter_pictures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='title',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Info'),
        ),
    ]
