# Generated by Django 4.0.3 on 2022-03-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия Организации')),
                ('tel_number1', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('tel_number2', models.CharField(max_length=13, null=True, verbose_name='Номер телефона2')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email pochta')),
                ('fax', models.CharField(max_length=9, null=True, verbose_name='Faks')),
            ],
        ),
    ]
