# Generated by Django 4.0.3 on 2022-03-18 12:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='Sovollar')),
                ('answer', models.TextField(verbose_name='Javoblar')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='info',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Информация'),
        ),
    ]
