# Generated by Django 4.0.3 on 2022-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
