# Generated by Django 4.0.3 on 2022-04-18 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_faq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='info_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='organization',
            name='info_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='organization',
            name='info_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Названия Организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Названия Организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Названия Организации'),
        ),
    ]
