# Generated by Django 4.0.3 on 2022-03-15 11:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('departament', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=35, verbose_name='F.I.O')),
                ('Tel', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
                ('Function', models.CharField(max_length=30)),
                ('Departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.departament')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.position')),
            ],
        ),
    ]
