# Generated by Django 4.0.3 on 2022-03-22 07:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='info',
            field=ckeditor.fields.RichTextField(verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Function',
            field=models.CharField(max_length=30, verbose_name='Funksiya'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Tel',
            field=models.CharField(max_length=13, verbose_name='Tel.Nomer'),
        ),
        migrations.AlterField(
            model_name='position',
            name='departament',
            field=models.CharField(max_length=30, verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Bo'lim nomi"),
        ),
    ]
