# Generated by Django 4.0.3 on 2022-03-18 12:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Main_image', models.ImageField(upload_to='')),
                ('Info', ckeditor.fields.RichTextField()),
                ('Data_Found', models.DateTimeField()),
                ('buy_or_not', models.BooleanField(default=False, verbose_name='Sotiladi')),
                ('Author', models.TextField()),
                ('Status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(max_length=30)),
                ('Data', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.order')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='Images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.commodity_images'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.commodity_type'),
        ),
    ]
