# Generated by Django 4.0.3 on 2022-03-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_order_detail_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='Order_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='commodity',
        ),
        migrations.AddField(
            model_name='commodity_type',
            name='Status',
            field=models.BooleanField(default=False, verbose_name='Sotiladi'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_detail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
