# Generated by Django 4.0.3 on 2022-04-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_remove_commodity_status_alter_commodity_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_images',
            name='images',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
