# Generated by Django 4.0.3 on 2022-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0007_alter_commodity_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='Main_image',
        ),
    ]
