# Generated by Django 4.0.3 on 2022-04-18 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0009_remove_commodity_images_commodity_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='Data_Found',
            new_name='data_Found',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='Info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='commodity_type',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='commodity_type',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='commodity',
            name='author_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Avtor'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='author_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Avtor'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='author_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Avtor'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='info_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='info_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='info_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='name_uz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commodity_type',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commodity_type',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commodity_type',
            name='name_uz',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
