# Generated by Django 4.0.3 on 2022-03-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_product_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Pay_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.pay'),
        ),
        migrations.AddField(
            model_name='order',
            name='Quanty',
            field=models.SmallIntegerField(default=0, verbose_name='Zakazlar soni'),
        ),
        migrations.AddField(
            model_name='order',
            name='Ship_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shiper'),
        ),
        migrations.AddField(
            model_name='order',
            name='Ship_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.BooleanField(default=False, verbose_name='Statusi'),
        ),
        migrations.AddField(
            model_name='order',
            name='SumProce',
            field=models.SmallIntegerField(default=0, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='Name',
            field=models.CharField(max_length=30, verbose_name='Tulov turi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
