# Generated by Django 4.0.3 on 2022-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_data_order_pay_type_order_quanty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Pay_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='Data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Narxi'),
        ),
    ]
